# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8e31c7bb3f5cd8ee48fb801b1d0ff667c8a19cc4cb4cf9e82733c3830ffc8591f62c9edc31338a300f55d723d2686bac01fe82ece92c03917b6a43ced8ec3a0

test:
  secret_key_base: 80db1767318503594827e433567a8398a13849653b81dd885828dfa278cbc3c7b54f8e43ea86e4de726f95d1abfd00438a6e15a0a67c7fd98c563e683df036c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
